language: rust
sudo: false
cache: cargo

os: linux

rust:
  - nightly
  - beta
  - stable
  - 1.38.0

jobs:
  allow_failures:
    - rust: nightly

script:
  - cargo test # current version of url
  - cargo update -p url --precise 1.7.1 && cargo test
  - cargo update -p url --precise 2.0.0 && cargo test
  - cargo update -p url --precise 2.1.1 && cargo test
